export const Vehicles = {
    "results" : 3,
    "vehicles" : [
        {
            "id" : "veh1",
            "new" : "false",
            "bestMatch": "true",
            "favorite" : "false",
            "superDealer": "false",
            "price" : 23344,
            "name" : "Audi A3",
            "description" : "1.4 TDI whatever",
            "descriptionType" : "Demo",
            "address" : "Audi center randburg",
            "rating" : 5,
            "image" : require("@/assets/img/audi-a3.jpg"),
            "logo" : require("@/assets/img/audi-logo.png"),
            "milage": "254000km",
            "model": "1398cc",
            "year": "2014"
        },
        {
            "id" : "veh2",
            "new" : "true",
            "bestMatch": "true",
            "favorite" : "true",
            "superDealer": "true",
            "price" : 23344,
            "name" : "Audi A4",
            "description" : "1.4 TSI",
            "descriptionType" : "Demo",
            "address" : "Audi center randburg",
            "rating" : 5,
            "image" : require("@/assets/img/audi-a4.jpg"),
            "logo" : require("@/assets/img/audi-logo.png"),
            "milage": "254000km",
            "model": "1398cc",
            "year": "2016"
        },
        {
            "id" : "veh2",
            "new" : "true",
            "bestMatch": "true",
            "favorite" : "true",
            "superDealer": "true",
            "price" : 23344,
            "name" : "Audi A4",
            "description" : "1.4 TSI",
            "descriptionType" : "Demo",
            "address" : "Audi center randburg",
            "rating" : 5,
            "image" : require("@/assets/img/audi-a4.jpg"),
            "logo" : require("@/assets/img/audi-logo.png"),
            "milage": "254000km",
            "model": "1398cc",
            "year": "2016"
        }
    ]
}

export const VehiclesAvailability = {
    "results" : 6,
    "vehicles" : [
        {
            "id" : "veh1",
            "date" : "2021-01-13T12:45:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep1.png"),
        },
        {
            "id" : "veh2",
            "date" : "2021-01-12T17:00:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep1.png")
        },
        {
            "id" : "veh3",
            "date" : "2021-01-14T09:55:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep2.png")
        },
        {
            "id" : "veh4",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep3.png"),
        },
        {
            "id" : "veh5",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep4.png")
        },
        {
            "id" : "veh6",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/EllipseCar.png"),
            "repimage" : require("@/assets/img/Executive/EllipseRep5.png")
        },
    ]
}

export const RefinedSearchResults = {
    "results" : 9,
    "vehicles" : [
        {
            "id" : "veh1",
            "date" : "2021-01-13T12:45:00Z",
            "name" : "Ford Fiesta",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/FordFiesta.png"),
            "superDealer": "true",
            "rating" : 4,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh2",
            "date" : "2021-01-12T17:00:00Z",
            "name" : "Opel Astra",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/OpelAstra.png"),
            "superDealer": "false",
            "rating" : 5,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh3",
            "date" : "2021-01-14T09:55:00Z",
            "name" : "Ford Puma",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "in-test-drive", 
            "image" : require("@/assets/img/Executive/FordPuma.png"),
            "superDealer": "true",
            "rating" : 4,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh4",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Fiat Punto",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/FiatPunto.png"),
            "superDealer": "true",
            "rating" : 5,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh5",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Volkswagen T-Roc",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "in-test-drive", 
            "image" : require("@/assets/img/Executive/VWTRoc.png"),
            "superDealer": "false",
            "rating" : 4,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh6",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "BMW X-Trail",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/BMWXTrail.png"),
            "superDealer": "true",
            "rating" : 5,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh7",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Kia Picanto",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "unavailable", 
            "image" : require("@/assets/img/Executive/KiaPicanto.png"),
            "superDealer": "false",
            "rating" : 4,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh8",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Opel Corsa",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "available", 
            "image" : require("@/assets/img/Executive/OpelCorsa.png"),
            "superDealer": "true",
            "rating" : 5,
            "address" : "Audi center randburg",
        },
        {
            "id" : "veh9",
            "date" : "2021-01-15T12:45:00Z",
            "name" : "Fiat 500L",
            "description" : "1.4 Tdci 67CV Elegance",
            "status": "unavailable", 
            "image" : require("@/assets/img/Executive/Fiat500L.png"),
            "superDealer": "false",
            "rating" : 4,
            "address" : "Audi center randburg",
        },
    ]
}
