import CustomTheme from '@/theme';
import { Platform, StatusBar, StyleSheet } from 'react-native';

const transparent = 'rgba(255, 255, 255, 0)';

export const styles = (props = {}) => StyleSheet.create({
    wrapperBlock: {
        flex: props.flex || 1,
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center',
        ...(props.transparentBackgroundColor ? {
                backgroundColor: props.transparentBackgroundColor,
            } : {
                backgroundColor: CustomTheme.colors[props.backgroundColor] || CustomTheme.colors.white,
            }
        ),
        position: props.position || 'relative',
        left: props.left || 0,
        bottom: props.bottom || 0,
        right: props.right || 0,
        top: props.top || 0,
        zIndex: props.zIndex || 0,
        width: props.width || 'auto',
        height: props.height || 'auto',
        minHeight: props.minHeight || 'auto',
        maxHeight: props.maxHeight || 'auto',
        paddingTop: props.paddingTop || Platform.OS === 'android' ? StatusBar.currentHeight : 0,
        paddingRight: props.paddingRight || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingLeft: props.paddingLeft || 0,
        marginBottom: props.marginBottom || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor] || transparent,
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        borderColor: CustomTheme.colors[props.borderColor] || transparent,
        borderWidth: props.borderWidth || 0
    },
    innerBlock: {
        flex: props.flex || 0,
        flexDirection: props.flexDirection || 'column',
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center',
        flexWrap: props.flexWrap || 'nowrap',
        ...(props.transparentBackgroundColor ? {
                backgroundColor: props.transparentBackgroundColor,
            } : {
                backgroundColor: CustomTheme.colors[props.backgroundColor] || CustomTheme.colors.white,
            }
        ),
        position: props.position || 'relative',
        width: props.width || 'auto',
        minWidth: props.minWidth || 'auto',
        height: props.height || 'auto',
        borderTopLeftRadius: props.borderTopLeftRadius || 0, 
        borderTopRightRadius: props.borderTopRightRadius || 0,
        borderBottomLeftRadius: props.borderBottomLeftRadius || 0, 
        borderBottomRightRadius: props.borderBottomRightRadius || 0,
        left: props.left || 0,
        top: props.top || 0,
        right: props.right || 0,
        bottom: props.bottom || 0,
        zIndex: props.zIndex || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingTop: props.paddingTop || 0,
        paddingRight: props.paddingRight || 0,
        paddingLeft: props.paddingLeft || 0,
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        overflow: props.overflow || 'hidden',
        ...(props.boxShadow ? {
                shadowColor: props.shadowColor || 'white',
                shadowOffset: {
                    width: props.shadowOffsetWidth || 0,
                    height: props.shadowOffsetHeight || 0,
                },
                shadowOpacity: props.shadowOpacity || 0,
                shadowRadius: props.shadowRadius || 3,
                ...(Platform.OS === 'android' && {
                        elevation: 5,
                    }
                ),
            } : {}
        ),
    },
    appText: {
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        paddingTop: props.paddingTop || 0,
        paddingRight: props.paddingRight || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingLeft: props.paddingLeft || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor] || transparent,
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        color: CustomTheme.colors[props.color],
        textTransform: props.textTransform || 'none',
        fontSize: props.fontSize || 15,
        fontWeight: props.fontWeight || '400',
        fontFamily: props.fontFamily || 'Poppins-Regular',
        width: props.width || 'auto',
        minWidth: props.minWidth || 'auto',
        height: props.height || 'auto',
        minHeight: props.minHeight || 'auto',
        lineHeight: props.lineHeight || 0,
        textAlign: props.textAlign || 'auto',
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        left: props.left || 0,
        top: props.top || 0,
        bottom: props.bottom || 0,
        right: props.right || 0,
        borderWidth: props.borderWidth || 0,
        borderColor: CustomTheme.colors[props.borderColor] || transparent
    },
    appInputText: {
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        paddingTop: props.paddingTop || 0,
        paddingRight: props.paddingRight || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingLeft: props.paddingLeft || 0,
        textTransform: props.textTransform || 'none',
        fontSize: props.fontSize || 15,
        fontWeight: props.fontWeight || '400',
        fontFamily: props.fontFamily || 'Poppins-Regular',
        width: props.width || 'auto',
        height: props.height || 'auto',
        lineHeight: props.lineHeight || 0,
        textAlign: props.textAlign || 'center',
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        left: props.left || 0,
        top: props.top || 0,
        ...(Platform.OS === 'android' ? {
                borderColor: CustomTheme.colors[props.borderTopColor] || transparent, 
                borderWidth: props.borderTopWidth || 0,
            } : {
                borderBottomColor: CustomTheme.colors[props.borderBottomColor],
                borderBottomWidth: props.borderBottomWidth || 0,
                borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
                borderTopWidth: props.borderTopWidth || 0,
                borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
                borderLeftWidth: props.borderLeftWidth || 0,
                borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
                borderRightWidth: props.borderRightWidth || 0,
            }
        ),
        backgroundColor: CustomTheme.colors[props.backgroundColor] || CustomTheme.colors.zircon,
        borderTopRightRadius: props.borderTopRightRadius || 0,
        borderTopLeftRadius: props.borderTopLeftRadius || 0,
        borderBottomLeftRadius: props.borderBottomLeftRadius || 0,
        borderBottomRightRadius: props.borderBottomRightRadius || 0
    },
    button: {
        backgroundColor: CustomTheme.colors[props.backgroundColor],
        color: CustomTheme.colors[props.color],
        shadowRadius: props.shadowRadius || 0,
        borderTopRightRadius: props.borderTopRightRadius || 0,
        borderTopLeftRadius: props.borderTopLeftRadius || 0,
        borderBottomLeftRadius: props.borderBottomLeftRadius || 0,
        borderBottomRightRadius: props.borderBottomRightRadius || 0,
        height: props.height || 'auto',
        width: props.width || 'auto',
        lineHeight: props.lineHeight || 0,
        fontSize: props.fontSize || 15,
        borderWidth: props.borderWidth || 0,
        borderColor: CustomTheme.colors[props.borderColor] || transparent,
        padding: props.padding || 0,
        paddingTop: props.paddingTop || 0,
        paddingBottom: props.paddingBottom || 0,
        marginTop: props.marginTop || 0,
        marginBottom: props.marginBottom || 0,
        marginLeft: props.marginLeft || 0,
        marginRight: props.marginRight || 0,
        ...(Platform.OS === 'android' ? {
                borderColor: CustomTheme.colors[props.borderTopColor] || transparent, 
                borderWidth: props.borderTopWidth || 0,
            } : {
                borderBottomColor: CustomTheme.colors[props.borderBottomColor],
                borderBottomWidth: props.borderBottomWidth || 0,
                borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
                borderTopWidth: props.borderTopWidth || 0,
                borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
                borderLeftWidth: props.borderLeftWidth || 0,
                borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
                borderRightWidth: props.borderRightWidth || 0,
            }
        ),
        flex: props.flex || 0,
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center',
        flexDirection: props.flexDirection || 'row',
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        left: props.left || 0,
        top: props.top || 0
    },
    image: {
        padding: props.padding || 0,
        width: props.width || 'auto',
        height: props.height || 'auto',
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        left: props.left || 0,
        right: props.right || 0,
        top: props.top || 0,
        bottom: props.bottom || 0,
        marginRight: props.marginRight || 0,
        marginTop: props.marginTop || 0,
        marginBottom: props.marginBottom || 0,
        marginLeft: props.marginLeft || 0
    },
    carousel: {
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        top: props.top || 0,
        left: props.left || 0,
        right: props.right || 0,
        bottom: props.bottom || 0,
        textAlign: props.textAlign || 'center',
        flexDirection: props.flexDirection || 'row',
        justifyContent: props.justifyContent || 'flex-start',
        alignItems: props.alignItems || 'flex-start',
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        width: props.width || 'auto',
        height: props.height || 'auto',
        color: CustomTheme.colors[props.color] || 'white',
    },
    carouselItem: {
        flex: props.flex || 0,
        textAlign: props.textAlign || 'center',
        flexDirection: props.flexDirection || 'column',
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center',
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        width: props.width || 'auto',
        height: props.height || 'auto',
        borderTopRightRadius: props.borderTopRightRadius || 0,
        borderTopLeftRadius: props.borderTopLeftRadius || 0,
        borderBottomLeftRadius: props.borderBottomLeftRadius || 0,
        borderBottomRightRadius: props.borderBottomRightRadius || 0,
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
    },
    carouselImage: {
        position: props.position || 'relative',
        zIndex: props.zIndex || 0,
        top: props.top || 0,
        left: props.left || 0,
        right: props.right || 0,
        bottom: props.bottom || 0,
        height: props.height || 'auto',
        width: props.width || 'auto',
    },
    slideshow: {
        position: 'absolute',
        zIndex: 5,
    },
    navigation: { 
        flexDirection: 'row', 
        justifyContent: 'center' 
    },
    screenTopNav: {
        position: props.position || 'relative',
        left: props.left || 14,
        flex: props.flex || 0,
        justifyContent: props.justifyContent || 'flex-start',
        alignItems: props.alignItems || 'center',
        flexDirection: props.flexDirection || 'row',
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        width: props.width || 'auto',
        height: props.height || 'auto',
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingTop: props.paddingTop || 0,
        paddingRight: props.paddingRight || 0,
        paddingLeft: props.paddingLeft || 0,
    },
    tile: {
        width: props.width || 130.25,
        height: props.height || 131.82,
        backgroundColor: CustomTheme.colors[props.backgroundColor] || CustomTheme.colors.white,
        marginLeft: props.marginLeft || 0,
        borderRadius: props.borderRadius || 0,
        flexDirection: props.flexDirection || 'column',
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center'
    },
    sliderBlock: {
        borderWidth: props.borderWidth || 0,
        borderColor: CustomTheme.colors[props.borderColor] || transparent,
        backgroundColor: CustomTheme.colors[props.backgroundColor] || transparent,
        position: props.position || 'relative',
        width: props.width || 'auto',
        height: props.height || 'auto',
        borderTopLeftRadius: props.borderTopLeftRadius || 0, 
        borderTopRightRadius: props.borderTopRightRadius || 0,
        left: props.left || 0,
        top: props.top || 0,
        zIndex: props.zIndex || 0,
        padding: props.padding || 0,
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        opacity: props.opacity || 1
    },
    scrollViewWrapper: {
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || 'black',
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || 'black',
        borderRightWidth: props.borderRightWidth || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor] || 'black',
        backgroundColor: CustomTheme.colors[props.backgroundColor] || transparent,
        borderBottomWidth: props.borderBottomWidth || 0,
        position: props.position || 'relative',
        width: props.width || 'auto',
        height: props.height || 'auto',
        left: props.left || 0,
        top: props.top || 0,
        zIndex: props.zIndex || 0,
        padding: 0,
    },
    card: {
        flex: props.flex || 0,
        flexDirection: props.flexDirection || 'column',
        justifyContent: props.justifyContent || 'center',
        alignItems: props.alignItems || 'center',
        backgroundColor: CustomTheme.colors[props.backgroundColor] || CustomTheme.colors.white,
        position: props.position || 'relative',
        width: props.width || 'auto',
        height: props.height || 'auto',
        borderTopLeftRadius: props.borderTopLeftRadius || 0, 
        borderTopRightRadius: props.borderTopRightRadius || 0,
        borderBottomLeftRadius: props.borderBottomLeftRadius || 0, 
        borderBottomRightRadius: props.borderBottomRightRadius || 0,
        left: props.left || 0,
        top: props.top || 0,
        right: props.right || 0,
        bottom: props.bottom || 0,
        zIndex: props.zIndex || 0,
        paddingBottom: props.paddingBottom || 0,
        paddingTop: props.paddingTop || 0,
        paddingRight: props.paddingRight || 0,
        paddingLeft: props.paddingLeft || 0,
        marginBottom: props.marginBottom || 0,
        marginTop: props.marginTop || 0,
        marginRight: props.marginRight || 0,
        marginLeft: props.marginLeft || 0,
        borderBottomColor: CustomTheme.colors[props.borderBottomColor],
        borderBottomWidth: props.borderBottomWidth || 0,
        borderTopColor: CustomTheme.colors[props.borderTopColor] || transparent,
        borderTopWidth: props.borderTopWidth || 0,
        borderLeftColor: CustomTheme.colors[props.borderLeftColor] || transparent,
        borderLeftWidth: props.borderLeftWidth || 0,
        borderRightColor: CustomTheme.colors[props.borderRightColor] || transparent,
        borderRightWidth: props.borderRightWidth || 0,
        overflow: props.overflow || 'hidden'
    }
});